export const AUTORIZACIONES = {
  // ACCESOS
  ADMINISTRAR_RENDICIONES: "SUBMODULO_ADMINISTRAR_RENDICIONES_GENERALES",
  CARGAR_RENDICIONES: "SUBMODULO_CARGAR_RENDICIONES_GENERALES",
} as const

export type Autorizacion = (typeof AUTORIZACIONES)[keyof typeof AUTORIZACIONES]
